#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                    ----[PlayerGUIAdvance]----                                     #
#                                     ----[By Loving11ish]----                                      #
#                                   ----[mc.crapticraft.com]----                                    #
#                                   ----[Plugin Config File]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Do you wish to use the GUI based /op feature?
Enable-op: true
#Do you wish to use the GUI based /deop feature?
Enable-deop: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Do you wish to use the GUI based player inventory view feature?
Enable-player-inventory: true
#Do you wish to use the GUI based player Enderchest view feature?
Enable-player-enderchest: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Do you wish to use the GUI based /mute feature?
Enable-mute: true
#Do you wish to use the GUI based /unmute feature?
Enable-unmute: true

Mute-command: 'mute %target% You have been muted by an operator'
Unmute-command: 'unmute %target%'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Do you wish to use the GUI based ban manager?
Enable-ban-manager: true

Enable-ban-1: true
Ban-length-1-material: 'PAPER'
Ban-length-1-name: "&cBan For 1 Hour!"
Ban-length-1-lore-1: "&aThis performs the /ban command"
Ban-length-1-lore-2: "&aand is issued by you, not the console."
Ban-length-1-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-1-command: 'ban %target% 1h You were temporarily banned for 1 hour by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-2: true
Ban-length-2-material: 'IRON_INGOT'
Ban-length-2-name: "&cBan For 1 Day!"
Ban-length-2-lore-1: "&aThis performs the /ban command"
Ban-length-2-lore-2: "&aand is issued by you, not the console."
Ban-length-2-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-2-command: 'ban %target% 1d You were temporarily banned for 1 day by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-3: true
Ban-length-3-material: 'ANVIL'
Ban-length-3-name: "&cBan For 3 Days!"
Ban-length-3-lore-1: "&aThis performs the /ban command"
Ban-length-3-lore-2: "&aand is issued by you, not the console."
Ban-length-3-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-3-command: 'ban %target% 3d You were temporarily banned for 3 days by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-4: true
Ban-length-4-material: 'IRON_BLOCK'
Ban-length-4-name: "&cBan For 7 Days!"
Ban-length-4-lore-1: "&aThis performs the /ban command"
Ban-length-4-lore-2: "&aand is issued by you, not the console."
Ban-length-4-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-4-command: 'ban %target% 7d You were temporarily banned for 7 days by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-5: true
Ban-length-5-material: 'OAK_PLANKS'
Ban-length-5-name: "&cBan For 2 Weeks!"
Ban-length-5-lore-1: "&aThis performs the /ban command"
Ban-length-5-lore-2: "&aand is issued by you, not the console."
Ban-length-5-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-5-command: 'ban %target% 2w You were temporarily banned for 2 weeks by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-6: true
Ban-length-6-material: 'STONE'
Ban-length-6-name: "&cBan For 1 Month!"
Ban-length-6-lore-1: "&aThis performs the /ban command"
Ban-length-6-lore-2: "&aand is issued by you, not the console."
Ban-length-6-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-6-command: 'ban %target% 1month You were temporarily banned for 1 month by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-7: true
Ban-length-7-material: 'MAGMA_BLOCK'
Ban-length-7-name: "&cBan For 3 Months!"
Ban-length-7-lore-1: "&aThis performs the /ban command"
Ban-length-7-lore-2: "&aand is issued by you, not the console."
Ban-length-7-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-7-command: 'ban %target% 3month You were temporarily banned for 3 months by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-8: true
Ban-length-8-material: 'OBSIDIAN'
Ban-length-8-name: "&cBan For 6 Months!"
Ban-length-8-lore-1: "&aThis performs the /ban command"
Ban-length-8-lore-2: "&aand is issued by you, not the console."
Ban-length-8-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-8-command: 'ban %target% 6month You were temporarily banned for 6 months by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
Enable-ban-9: true
Ban-length-9-material: 'BEDROCK'
Ban-length-9-name: "&cPerm Ban This Player!"
Ban-length-9-lore-1: "&aThis performs the /ban command"
Ban-length-9-lore-2: "&aand is issued by you, not the console."
Ban-length-9-lore-3: "&dYOU REQUIRE BAN PERMISSIONS FOR THIS TO WORK!"

Ban-length-9-command: 'ban %target% You were permanently banned by an operator'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Do you wish to have the banned player say a final message?
Enable-banned-player-message: true

Banned-player-message: "&cOh dear, I got banned! :-("
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                    ----[PlayerGUIAdvance]----                                     #
#                                     ----[By Loving11ish]----                                      #
#                                   ----[mc.crapticraft.com]----                                    #
#                                 ----[Plugin Messages Config]----                                  #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#GUI Name configurations.

#Player list GUI name:
Player-list-menu-title: "&bPlayer List"

#Actions GUI name:
#If an error occurs, ensure that the '%target%' is present within the title name.
Actions-menu-title: "&bActions: %target%"

#Ban manager GUI name:
#If an error occurs, ensure that the '%target%' is present within the title name.
Ban-manager-nemu-title: "&bBan: %target%"

#Punish menu GUI name:
#If an error occurs, ensure that the '%target%' is present within the title name.
Punish-menu-title: "&bPunish: %target%"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Plugin messages

Player-list-menu-last-page: "&7You are on the last page."
Player-list-menu-first-page: "&7You are on the first page."
Player-list-command-no-permission: "&4You do not have the permission &eplayergui.use &4needed to run that command"

#If an error occurs, ensure that the '%target%' is present
Actions-command-invalid-player: "&cThe player &e%target% &ccould not be found!"
Actions-command-no-player-provided: "&cPlease provide a player to moderate. /actions <player>"
Actions-command-no-permission: "&4You do not have the permission &eplayergui.mod &4needed to run that command"

#If an error occurs, ensure that the '%target%' is present
Punish-command-invalid-player: "&cThe player &e%target% &ccould not be found!"
Punish-command-no-player-provided: "&cPlease provide a player to moderate. /punish <player>"
Punish-command-no-permission: "&4You do not have the permission &eplayergui.ban &4needed to run that command"

Help-command-no-permission: "&4You do not have the permission &eplayergui.help &4needed to run that command"

Reload-command-no-permission: "&4You do not have the permission &eplayergui.reload &4needed to run that command"

#Show-command-VanishAPI-not-detected:
Show-1: "&4This command is only active if either SuperVanish or PremiumVanish are installed!"
Show-2: "&4SuperVanish: &dhttps://www.spigotmc.org/resources/supervanish-be-invisible.1331/"
Show-3: "&4PremiumVanish: &dhttps://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/"
Show-command-player-visible: "&eYou are now visible to other players"
Show-command-no-permission: "&4You do not have the permission &eplayergui.show &4needed to run that command"

#Vanish-command-VanishAPI-not-detected:
Vanish-1: "&4This command is only active if either SuperVanish or PremiumVanish are installed!"
Vanish-2: "&4SuperVanish: &dhttps://www.spigotmc.org/resources/supervanish-be-invisible.1331/"
Vanish-3: "&4PremiumVanish: &dhttps://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/"
Vanish-command-player-invisible: "&eYou are now invisible to other players"
Vanish-command-no-permission: "&4You do not have the permission &eplayergui.vanish &4needed to run that command"

#Plugin-update-available:
Update-1: "&4*-------------------------------------------*"
Update-2: "&b[PlayerGUIAdvanced] &c- A new version is available!"
Update-3: "&4*-------------------------------------------*"

#Plugin-no-new-update:
No-update-1: "&a*-------------------------------------------*"
No-update-2: "&b[PlayerGUIAdvanced] &a- Plugin is up to date!"
No-update-3: "&a*-------------------------------------------*"
Update-check-failure: "&b[PlayerGUIAdvanced] &4- Unable to check for updates! - &c"

Player-only-command: "&4That command can only be executed by a player."

Plugin-reload-successful: "&aThe config file has been reloaded!"

#Incorrect-command-syntax-console:
Syntax-error-1: "&4Please provide an argument!"
Syntax-error-2: "&4pl reload"
Syntax-error-3: "&4pl help"

Targeted-player-op-successful: "&ePlayer %target% has been successfully made an op!"
Targeted-player-deop-successful: "&ePlayer %target% has been successfully removed from op!"

Player-op-no-permission: "&4You do not have the permission &eplayergui.op"
Player-deop-no-permission: "&4You do not have the permission &eplayergui.deop"
Player-ban-no-permission: "&4You do not have the permission &eplayergui.ban"

Target-ban-exempt: "&cThat player is exempt from bans!"

Disabled-GUI-Feature: "&cThis feature has been disabled by an admin!"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Plugin-help-chat-menu
Help-1: "&e[---------------- &b[PlayerGUIAdvanced] &e-----------------]"
Help-2: "&f/actions <player> &7- &dThis command opens up the Actions GUI."
Help-3: "&f/punish <player> &7- &dThis command opens up the Punish GUI."
Help-4: "&f/players &7- &dThis command opens up the Player List GUI."
Help-5: "&f/pl reload &7- &dThis command reloads the plugin config file."
Help-6: "&f/pl vanish &7- &dThis command sets you into vanish."
Help-7: "&f/pl show &7- &dThis command sets you out of vanish."
Help-8: "&f/pl help &7- &dThis command shows this help menu."
Help-9: "&e[-------------------- &bPermissions &e---------------------]"
Help-10: "&f                               playergui.use"
Help-11: "&f                               playergui.mod"
Help-12: "&f                               playergui.ban"
Help-13: "&f                               playergui.op"
Help-14: "&f                               playergui.deop"
Help-15: "&f                               playergui.exempt"
Help-16: "&f                               playergui.vanish"
Help-17: "&f                               playergui.show"
Help-18: "&f                               playergui.help"
Help-19: "&f                               playergui.reload"
Help-20: "&f                               playergui.update"
Help-21: "&e[----------------------------------------------------]"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#